import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center justify-center min-h-screen">
          <div className="p-8 bg-white rounded-lg shadow-md min-w-80">
            <Link href={"/"} className="flex justify-center mb-4">
              <Image src={"/logo.svg"} width={40} height={40} alt="logo" />
            </Link>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
